name: Comment Floodgate
description: Automatically lock issues if they get flooded with comments.

inputs:
  repo-token:
    description: >-
      The automatic GITHUB_TOKEN secret.
    required: false
    default: ${{ github.token }}

  minutes-in-period:
    description: >-
      The number of minutes in the time period.
      Must be an integer greater than 0.
    required: false
    default: 60

  max-comments-per-period:
    description: >-
      How many comment reactions per time period are allowed before this action
      locks an issue (use 0 to disable).
    required: false
    default: 12

  lock-message:
    description: >-
      The comment that this action posts when it locks an issue.
      The first `{{maxCommentsPerPeriod}}` string (no spaces) is replaced by the
      `max-comments-per-period` input.
      The first `{{minutesInPeriod}}` string (no spaces) is replaced by the
      `minutes-in-period` input.
    required: false
    default: >-
      This issue is seeing a lot of traffic
      ({{maxCommentsPerPeriod}} new comments
      in only {{minutesInPeriod}} minutes!),
      so we’re going to lock it to just collaborators for now,
      in a cooldown period.

  lock-reason:
    description: >-
      The reason for locking the issue or pull request conversation.
      Lock will fail if you don't use one of these reasons:
      `off-topic`, `too heated`, `resolved`, or `spam`.
    required: false
    default: too heated

runs:
  using: node12
  main: dist/index.js

branding:
  icon: cloud-rain
  color: blue
